Search category price
GuilhermePeyflo/search-engine pull request #1
Opened 2021-05-13 16:43 UTC by nadiavhansen

2021-05-13 17:18 UTC, GuilhermePeyflo requested changes
Alterar o retorno que vem do banco para retornar uma lista

2021-05-13 18:00 UTC, GuilhermePeyflo approved these changes

2021-05-13 20:07 UTC, yuripiffer requested changes
Muito bom! Continuem assim!!!

2021-05-13 20:07 UTC, yuripiffer commented on Database/DataBase.py
> +            print(queries["category"])
freedom for print!
Leave print alone!!!

2021-05-13 20:07 UTC, yuripiffer commented on Database/DataBase.py
> +        if len(queries["category"]) > 1:
Talvez mudar o if para for len(x)... se tiver só 1 elemento, faz uma única vez

2021-05-14 11:20 UTC, yuripiffer approved these changes

2021-05-14 14:24 UTC, closed without merging